### ISSUE TITLE
Feature request:  Space oar

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#102]
#### Description of issue
This is the lowest priority ticket you will ever receive.

We're going back in time.  Time to reduce the number of engines and force some crew to assist in propelling the ship with Nanotrasen's patented space oar.  Converts pretty readily into standard boat oar as we devolve through time.

Picture.  The ship is getting swarmed with space carp.  What do people usually do?  They hide where it's safe.  Places with no windows.  Not anymore.  With the space oar, if you want to get away, you'd better get to the oar-equipped windows and start moving that ship!

#### Difference between expected and actual behavior
No power required for this, just chumps manning the oars.  

#### Steps to reproduce
This is not an ERP game.  Inappropriate questions will not be answered.

#### Specific information for locating

That's up to you.  I ain't code jockey

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
Going to close this as it's not something I can see being implemented exactly as-is (as discussed on Discord) - but I will add a note to the projects about needing some kind of manual thrust system to be added.
