### ISSUE TITLE
Newscaster events need OOPs friendly re-write

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/Baystation12#104]

**Comment by ZirconiumWit** [comment]
author = "Junior editor 'Cal'"
    channel_name = "Tradehouse Times"
    message = {"Hnnnnnnare your business yiiiings growing munnnnchrooms in the toiiiilets?  We audited thirtyyy bussssinessesss.  Hhhhhthe results were disguuuusting."}

    channel_name = "Mercantilism Daily Digest "
    author = "Field Research Assistant Belin Stovchik, narrated by Yoff D'erkshol"
    message = {"There have been a troubling number of reports that baxxid are being assaulted and dismembered for their claws.  Rumors abound regarding the true nature of a disembodied Baxxid claw.  However, sometimes we as a civilization have a tendency to let our imaginations run amok.  Today, I would like to share my findings with regards to a material that is gaining something of an urban legend status.  It has been said that these claws can be crushed into powder to yield renewed youth.  Through rigorous testing of dubiously legal samples, our team of researchers have concluded that there is no truth to these myths.  Please, leave our insectile friends alone and intact"}

**Comment by MistakeNot4892** [comment]
Closing this so it goes off the issue list, please feel free to keep posting (or PM on Discord, w/e)
