### ISSUE TITLE
View relationship hyperlink doesn't work

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#128]
#### Description of issue
When relations are possible, a pop-up un chat appears, advising to finalize messages with a link. the link always leads to an empty relationships window.

#### Difference between expected and actual behavior
The link should lead to the same window that clicking the button does. itt does not.

#### Steps to reproduce

Have someone spawn, and get the relationship chance.

#### Specific information for locating

See above?

#### Length of time in which bug has been known to occur

At least a few days

#### Client version, Server revision & Game ID

???

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by SodiumShine** [comment]
I was unable to replicate this issue. Tested it live with another person and it worked fine.

**Comment by SodiumShine** [comment]
Issue confirmed. Link at roundstart does not do the same as the verb, and it should.
