### ISSUE TITLE
Add Ui button to open clothing-based pockets

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#144]
#### Description of issue

Would really like a button on screen, like the welding mask button, to open up equipted clothe's pockets (See Tradecoat two pockets)

#### Difference between expected and actual behavior
A request.
Currently, you need to open your full worn tree, and click on your clothe, and hope you don't drag them too much when you do, or some other issue

#### Steps to reproduce

Man, I aint a coder

#### Specific information for locating

Not in lady jeans. Shit got no pockets

#### Length of time in which bug has been known to occur

?!?!

#### Client version, Server revision & Game ID

1//1

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
This is easy enough to do for suits but isn't really doable for storage accessories without some finnagling.
