### ISSUE TITLE
Some objectives are impossible.

### ISSUE THREAD

**Issue by MistakeNot4892** [ScavStation/Baystation12#146]
See  #145

**Comment by zacklucky7** [comment]
For reference as posted by Six on Discord:

- Theft objective can't be completed due to the items it wants not existing on the map
- Brig objective can't be completed due to lacking a brig (to be discussed about dropping entirely)
- note to self: review other goals

**Comment by zacklucky7** [comment]
Thoughts on theft objective changes:

- Hypospray -> Mobile Defibrillator or Surgical Kit?
- Secret Documents item? (per Winter on Discord)
