### ISSUE TITLE
Yinglet Fireaxe use broken (Possibly other two-handed)

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#151]
#### Description of issue

Since the size update, Yinglets cannot properly use two-handed tools like the fireaxe. They cannot weild them.

#### Difference between expected and actual behavior
Yinglets should be able to use two handed equiptment if they have two hands. They cannot

#### Steps to reproduce
Go to atmo, and get Fireaxe. Have two empty hands, and pick axe up. Use it on nearby door. It should take around four hits to break two handed, but will instead take upwards of 15. Once door is broken, attempt to use fire axe to pry door open. You will be told you need to be weilding the axe to do this

#### Specific information for locating

Fireaxe, yinglet, door.

#### Length of time in which bug has been known to occur

At least since the Yinglet update where they where made small

#### Client version, Server revision & Game ID

!?!!

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
This is due to their smallness.
I've added a message to the airlock interaction to indicate why it's not working.
