### ISSUE TITLE
Molitov won't burn if can't drop fuel on floor to burn

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#178]
#### Description of issue

Breaking a lit molitov via throwing on ground won't cause any fire if the ground tile it breaks on has filth on it. Filth also seems to hinder bottle breaking?

#### Difference between expected and actual behavior

Molitov makes inferno regardless of how dirty floor is, and breaks in a single throw

#### Steps to reproduce
 grab a fresh beer, pop it open, stuff in a rag, and light the fucker. Find a dirty spot of floor to purge with fire and fail horribly

#### Specific information for locating

Bottle o' booze, filth, fire

#### Length of time in which bug has been known to occur

At least since molitov update?

#### Client version, Server revision & Game ID

????

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MistakeNot4892** [comment]
Tried to reproduce this a few times, definitely just seems to be a case of throwing on harm intent.
