### ISSUE TITLE
Instruct verb does not appear to allow all skills

### ISSUE THREAD

**Issue by zacklucky7** [ScavStation/Baystation12#185]
#### Description of issue

When using the 'Instruct' verb, not all skills appear.

For example, I needed dialysis done, but it doesn't appear without basic skill in Medicine. I tried to use the Instruct verb to give skill to another player, but my only choice was Finance.

I had multiple skills that the target did not have, but could only instruct in Finance.

#### Difference between expected and actual behavior

Expected: All skills higher than the target's skill level appears
Actual: Only Finance seems to appear?

#### Steps to reproduce

1. Have two players -- one has skills, the other does not.
2. The player with skills (A) uses the Instruct verb and selects the player without skills (B).
3. A only has the choice to instruct in Finance, or possibly nothing, if Finance isn't there.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by afterthought2** [comment]
There are more restrictions on what Instruct allows than `player A's skill X is higher than player B's skill X`. You must be at least expert level (second highest) and they must be untrained (lowest).

**Comment by zacklucky7** [comment]
Confirmed not a bug by testing master vs untrained -- thanks @afterthought2
