### ISSUE TITLE
Crafting steps are unclear and need some kind of hint or guide system

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#244]
Figuring out how to do things is hard. Beyond just the using a stack of steel plates in your hand, how you can combine the things you make isn't written anywhere. I can make most the parts to a pneumatic cannon, and a turret base, but I can't figure out how to expand these. Further things are also unknown, like how to construct re-enforced walls, or how to fix busted up doors.

**Comment by MistakeNot4892** [comment]
Crafting guide is in, turrets/doors/walls are really stuff that needs codex entries rather than crafting hints.
