### ISSUE TITLE
Malfunctioning Syringe transfer quantities

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#273]
On the start of my first shift back on the Ivenmoth Tradeship, I had noticed many things had changed. This is none of my business.
What is of my business is the syringes I intended to use to apply medicine. They seem to have been mis-stored, as they do not move at a higher rate then 5u per load, despite clearly being labled as rated up to their capacity of 15. Time is of the essence when it comes to medicine, and needing to jab someone three times instead of one can be the difference between braindeath, and irritation.

**Comment by SodiumShine** [comment]
Related to #275

**Comment by MistakeNot4892** [comment]
Closed along with #275
