### ISSUE TITLE
Junior Researcher does not have robotics access

### ISSUE THREAD

**Issue by zacklucky7** [ScavStation/Baystation12#274]
#### Description of issue

Junior Researcher does not have robotics access, so they can't do any internal cyborg maintenance or use the exosuit fabricator. This behaviour also extends to Enclave Patriarch.

#### Issue bingo

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by SodiumShine** [comment]
#198 related
