### ISSUE TITLE
transfer amounts don't work

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#275]
#### Description of issue
Transfer amounts can't seem to be set.

#### Difference between expected and actual behavior
Expected: when you right click a beaker and select 'change transfer amount' that you could change transfer amount
actual: Nothing really happens when you select this option

#### Steps to reproduce
Find a syringe, or a beaker, or a cup of coffee, right click it in your hand, and go wild.  

#### Specific information for locating

there seems to be no item that this works on, so you can find this on any reagent-holding item.

#### Length of time in which bug has been known to occur

Since server started, tbh.

#### Client version, Server revision & Game ID

current version

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by TheKnightofAura** [comment]
As an additional note, Spray bottles USED to be able to adjust their quantity. I remember swapping between 5 and 10 units. But the button for it is entirely gone now
