### ISSUE TITLE
autolathe won't gib back what it took

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#276]
#### Description of issue
You put in materials in the autolathe.  It claims it's willing to eject these materials.  It lies.

#### Difference between expected and actual behavior
The material eject button should eject material.

It doesn't

#### Steps to reproduce
Insert material in the autolathe in engineering.  Then, eject it.

#### Specific information for locating

It's in the lower tool storage below engineering. 

#### Length of time in which bug has been known to occur

This past week, probably longer, but I didn't check it before this past week.

#### Client version, Server revision & Game ID

Current as of 2/2/20

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by afterthought2** [comment]
Possible this was accidentally fixed in #256. There was certainly some issue along these lines that I noticed, but I didn't test if it worked.
