### ISSUE TITLE
Disappearing chairs

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#305]
#### Description of issue
Sat in a glass chair with black cloth made by Aura.  I rotated the chair with an alt click, and got up.  The chair disappeared.  The chair reappeared when I sat back down on it.  And disappeared once more when I got up.

#### Difference between expected and actual behavior
Chairs are best when visible.

#### Steps to reproduce
Rotate chairs so they're facing away from the viewer.  This was repeatable for a plasteel chair.

#### Length of time in which bug has been known to occur

Discovered today, 2/4/2020

#### Client version, Server revision & Game ID

Client Version: 512
Server Revision: be72e4ea46190c77842057d10c8c972925b13299 - tradeship - 2020-02-04
Game ID: b5x-dAWT
Current map: Tradeship Ivenmoth

#### Issue bingo

- [ x] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by TheKnightofAura** [comment]
Also the north-facing chair in the lounge now renders incorrectly entirely under the player when they sit in it

**Comment by MistakeNot4892** [comment]
note to self: reapply missing north overlay in chair/on_update_icon

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/73823462-6c4e3300-484c-11ea-892f-58830c859144.png)
Can't reproduce this on latest dev.

**Comment by MistakeNot4892** [comment]
Never mind, unbuckling did it.
