### ISSUE TITLE
Helium is lame

### ISSUE THREAD

**Issue by ZirconiumWit** [ScavStation/Baystation12#308]
#### Description of issue
I breathed a bunch of helium today and no high pitched squeaky voice!  Well.  No higher than usual.

#### Difference between expected and actual behavior
Helium should make voices squeaky

#### Steps to reproduce
Breathe helium.  Get NOTHING.

#### Specific information for locating

Any helium filled environment.

#### Length of time in which bug has been known to occur

Today only

#### Client version, Server revision & Game ID

Same as the last two

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by ZirconiumWit** [comment]
Actually helium is pretty awesome now again.  I'm squeaking for a long time AFTER I inhaled about 700 kpa worth of a large air tank of helium.  Might have been lag.

**Comment by TheKnightofAura** [comment]
There is something odd about helium tanks, though. I opened one and released 2000kPa into the air, and while it did make all the airlocks close, it didn't make anyone squeak

**Comment by MistakeNot4892** [comment]
![image](https://user-images.githubusercontent.com/2468979/73830021-09629900-4858-11ea-8124-b4b6c8380f6c.png)

It takes a bit for it to enter the bloodstream and various other speech effects might block it, like slurry. Either way, can't reproduce locally.

**Comment by ZirconiumWit** [comment]
note - the 2000 kpa worth of helium was put out via a cannister, not a tank.  Also, this was in cargo, which opens into four floors.  While it was used in upper cargo, which should restrict it to 2 floors, I wonder if it was just too large an area for that helium shenanegan to have gone off properly
