### ISSUE TITLE
Screen goes black when draging welding mask toggle icon to hands

### ISSUE THREAD

**Issue by TheKnightofAura** [ScavStation/Baystation12#84]
#### Description of issue
Screen goes black, and all UI removed when dragging icon

#### Difference between expected and actual behavior
???? happens, since it was a mistake in the first place. Probably nothing? Maybe unequipts welding mask? def doesn't require restart to continue playing

#### Steps to reproduce
Be yinglet, wear welding mask, have empty hands. Look at top left of screen, and click+drag the welding mask icon to an empty hand. Screen should go black, and all UI should vanish.

#### Specific information for locating

Welding mask, Yinglet

#### Length of time in which bug has been known to occur
I just found it three hours ago

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by SodiumShine** [comment]
Can confirm this works with potentially any item that produces toggle buttons in the top left of the HUD. It also works with humans. (Tested with hardsuit and helmet on both human and yinglet)

View is actually returned with ghosting, but that's not very helpful.

**Comment by SodiumShine** [comment]
`[23:34:57] Runtime in movable_screen_objects.dm,49: type mismatch: "15x15" + 1
  proc name: encode screen X (/obj/screen/movable/proc/encode_screen_X)
  usr: Elliott Mull (/mob/living/carbon/human) ([0x300003c]) (the open space) (42,32,2) (/turf/simulated/open) (sodiumshine)
  usr.loc: The open space (/turf/simulated/open) ([0x10022d9]) (42,32,2) (/area/ship/scrap/cargo)
  src: Toggle Headlamp (/obj/screen/movable/action_button)
  src.loc: null
  call stack:
  Toggle Headlamp (/obj/screen/movable/action_button): encode screen X(8, Elliott Mull (/mob/living/carbon/human))
  Toggle Headlamp (/obj/screen/movable/action_button): MouseDrop(Elliott Mull (/mob/living/carbon/human), null, the open space (42,32,2) (/turf/simulated/open), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=25;left=1;scr...")
  SodiumShine (/client): MouseDrop(Toggle Headlamp (/obj/screen/movable/action_button), Elliott Mull (/mob/living/carbon/human), null, the open space (42,32,2) (/turf/simulated/open), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=25;left=1;scr...")
[23:34:57] Runtime in movable_screen_objects.dm,74: type mismatch: "15x15" + 1
  proc name: encode screen Y (/obj/screen/movable/proc/encode_screen_Y)
  usr: Elliott Mull (/mob/living/carbon/human) ([0x300003c]) (the open space) (42,32,2) (/turf/simulated/open) (sodiumshine)
  usr.loc: The open space (/turf/simulated/open) ([0x10022d9]) (42,32,2) (/area/ship/scrap/cargo)
  src: Toggle Headlamp (/obj/screen/movable/action_button)
  src.loc: null
  call stack:
  Toggle Headlamp (/obj/screen/movable/action_button): encode screen Y(8, Elliott Mull (/mob/living/carbon/human))
  Toggle Headlamp (/obj/screen/movable/action_button): MouseDrop(Elliott Mull (/mob/living/carbon/human), null, the open space (42,32,2) (/turf/simulated/open), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=25;left=1;scr...")
  SodiumShine (/client): MouseDrop(Toggle Headlamp (/obj/screen/movable/action_button), Elliott Mull (/mob/living/carbon/human), null, the open space (42,32,2) (/turf/simulated/open), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=25;left=1;scr...")`
