### ISSUE TITLE
Robot role spawns incorrectly on round start.

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/Baystation12#90]
> 18:10] Winter: i got a landmark down for Robot, and sure enough when i ready up with robot selected as my highest priority a default cyborg body spawns on the landmark.
However, i'm not IN The body, and i get errors regarding how the spawnpoint cannot be found

This also occurred in a room with a cryopod for robots and an oversight console.

`## WARNING: Could not find an appropriate spawnpoint for job Robot`

`Your chosen spawnpoint (Cryogenic Storage) is unavailable for your chosen job (Robot). Spawning you at another spawn point instead.
`

**Comment by MistakeNot4892** [comment]
This seems to be down to something changing the order that minds and mobs initialize so the key is being set repeatedly - spawnpoints are easily fixed but the join bug is being more of a pain.
