### ISSUE TITLE
Power monitor won't run on junior engineer PDA.

### ISSUE THREAD

**Issue by SodiumShine** [ScavStation/Baystation12#98]
E-mailing the power monitor software from a console to a PDA (at least this being the Jr. Engineer PDA), does not allow it to run. Clicking the button for it on the main menu produces a sound effect but does not change the menu or provide any other feedback.

The power monitor software is access restricted, but Jr. Engineers have that access, and can also use it via a console.

Unsure if works via other file transfer methods or other PDA.

**Comment by MistakeNot4892** [comment]
So - after a bunch of poking we have discovered that PDAs need the PROGRAM_PDA usage flag, and the power monitor doesn't have it. Not a bug - get a laptop or tablet from loadout if you want to run the power monitor. This can be changed if required but yeah not a problem with the code after all.
